.TH FILE_TRANSFER 1 2022-10-01 "" "file_transfer"
.SH NAME
file_transfer \- file_transfer(localfile)
.SH SYNOPSIS
\fIfile_transfer(localfile)\fR
.SH OPTIONS
.PP
\fBlocalfile\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.file_transfer at http.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
