.TH HTTP_SUCCESS 1 2025-May "" "http_success"
.SH NAME
http_success \- http_success(data,
    <i>s</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIhttp_success(data,
    <i>s</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBdata\fB \fR\- . 
.PP
.PP
\fBs\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.http_success at http.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
