.TH HTTP_ERROR 1 2024-May "" "http_error"
.SH NAME
http_error \- http_error(data,
    <i>err</i> = <span style='color: green;'>500</span>)
.SH SYNOPSIS
\fIhttp_error(data,
    <i>err</i> = <span style='color: green;'>500</span>)\fR
.SH OPTIONS
.PP
\fBdata\fB \fR\- . 
.PP
.PP
\fBerr\fB \fR\- 500. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.http_error at http.R:line 23
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
