.\" man page create by R# package system.
.TH ROUTER 1 2000-Jan "handle" "handle"
.SH NAME
handle \- 
.SH SYNOPSIS
\fIhandle(\fBreq\fR as <generic> HttpRequest, 
\fBresponse\fR as <generic> HttpResponse, 
\fBrouter\fR as <generic> Router, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
router
.SH FILES
.PP
RwebHost.dll
.PP
