.\" man page create by R# package system.
.TH HTTP 4 2000-Jan "host_file" "host_file"
.SH NAME
host_file \- 
.SH SYNOPSIS
\fIhost_file(\fBwww\fR as <generic> WebFileSystemListener, 
\fBreq\fR as <generic> HttpRequest, 
\fBresponse\fR as <generic> HttpResponse);\fR
.SH SEE ALSO
http
.SH FILES
.PP
RwebHost.dll
.PP
